# Generated by Django 5.1.3 on 2024-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's name", max_length=100)),
                ('title', models.CharField(help_text="Client's title or occupation", max_length=100)),
                ('description', models.TextField(help_text='Testimonial content')),
                ('photo', models.ImageField(blank=True, default='test_photos/default.gif', null=True, upload_to='test_photos/')),
            ],
        ),
    ]
