# Generated by Django 5.1.3 on 2024-11-13 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Name of the author', max_length=100)),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('description', models.TextField(help_text='Content of the blog post')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date when the blog was created')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', null=True, unique=True)),
                ('tag', models.CharField(help_text='Tag for the blog post', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Blog post image', null=True, upload_to='blog_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='User comment text')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date when the comment was created')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fruitkha.blog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fruitkha.comment')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='fruitkha.account')),
            ],
        ),
    ]
