# Generated by Django 5.1.3 on 2024-11-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0003_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(help_text='Background image for the slider', upload_to='slider_photos/'),
        ),
    ]
