# Generated by Django 5.1.3 on 2024-11-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0008_alter_slider_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text_align',
            field=models.CharField(choices=[('col-lg-10 offset-lg-1 text-center', 'Center Align'), ('col-lg-10 offset-lg-1 text-right', 'Right Align'), ('col-md-12 col-lg-7 offset-lg-1 offset-xl-0', 'Left Align')], default='col-lg-10 offset-lg-1 text-center', help_text='Text alignment for the slider content', max_length=200),
        ),
    ]
