# Generated by Django 5.1.3 on 2024-11-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0010_alter_slider_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text_align',
            field=models.CharField(choices=[('col-md-12 col-lg-7 offset-lg-1 offset-xl-0', 'Left Align'), ('text-center', 'Center Align'), ('text-right', 'Right Align')], default='text-center', help_text='Text alignment for the slider content', max_length=250),
        ),
    ]
