# Generated by Django 5.1.3 on 2024-11-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0012_alter_slider_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.CharField(blank=True, help_text='Coupon code for discount', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_users', to='fruitkha.account'),
        ),
    ]
