# Generated by Django 5.1.3 on 2024-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0015_cartitem_discount_cartitem_subtotal_cartitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_address', models.TextField(help_text='Shop address')),
                ('shop_hours', models.TextField(help_text='Operating hours of the shop')),
                ('phone', models.CharField(help_text='Shop phone number', max_length=15)),
                ('email', models.EmailField(help_text='Shop contact email', max_length=254)),
                ('google_map_embed', models.TextField(help_text='Embed link for Google Maps')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('x', models.URLField(blank=True, help_text='X (formerly Twitter) URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub URL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person sending the message', max_length=100)),
                ('email', models.EmailField(help_text='Email of the person sending the message', max_length=254)),
                ('phone', models.CharField(help_text='Phone number of the person sending the message', max_length=15)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='The message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the subscriber', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user subscribed')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team member', max_length=100)),
                ('role', models.CharField(help_text='Role of the team member', max_length=250)),
                ('photo', models.ImageField(blank=True, default='team_photos/team_default-1.jpg', help_text='Team member image', null=True, upload_to='team_photos/')),
                ('facebook', models.URLField(blank=True, help_text='Facebook account of the team member', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn account of the team member', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub account of the team member', null=True)),
            ],
        ),
    ]
