# Generated by Django 5.1.3 on 2024-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha', '0016_contactdetails_contactmessage_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('strawberry', 'Strawberry'), ('berry', 'Berry'), ('lemon', 'Lemon'), ('apple', 'Apple'), ('avocado', 'Avocado')], help_text='Category of the product', max_length=50),
        ),
    ]
